### PR TITLE
186 verify i can access where the data is stored that i need

### PR DESCRIPTION
**Pull request by mariotorres1**

### CODE REVIEW

**Comment by mariotorres1** [comment]
I'm not going to fix that linter issue, I'm able to access the variable this way and I haven't figured a way to access it while fixing that linter issue with the way we have our project set up currently

**Comment by mariotorres1** [comment]
Never mind, I found a work around the issue

**Review by katerosenthal — APPROVED** [review]

**Review by BSU-EzekielHolmes — APPROVED** [review]
Good.

**Comment by mariotorres1** [comment]
This task took about 30 minutes in total.

**Pull request merged**
