### PR TITLE
227 display highest and lowest pressure range on the heat map

### PR DESCRIPTION
**Pull request by mitchcrocker**

### CODE REVIEW

**Comment by mitchcrocker** [comment]
Code does work, linter failures are resolved once the draw button is pressed

**Comment by mitchcrocker** [comment]
I'm unable to figure out how to pass the linter, it's not picking up that the two variables are defined in resultsParser.js and continues to flag them. Code is good to merge and works perfectly fine.

**Comment by mitchcrocker** [comment]
now passes linter

**Review by mariotorres1 — APPROVED** [review]

**Comment by mariotorres1** [comment]
There is a bug when the window is resized it adds a second heatmap key below the first one

**Comment by mariotorres1** [comment]
Every time the window is resized it adds another one. It's essentially appending another child in the html every time the window if resized. Probably a easy fix

**Review by mariotorres1 — CHANGES_REQUESTED** [review]
For small bug fix, I commented above the issue

**Review by mariotorres1 — APPROVED** [review]

**Review by katerosenthal — APPROVED** [review]

**Pull request merged**
