### PR TITLE
121 create skeleton of node class

### PR DESCRIPTION
**Pull request by mariotorres1**

### CODE REVIEW

**Comment by mariotorres1** [comment]
Simple skeleton file, more than likely will be adjusted as I continue to build on it.

**Comment by mariotorres1** [comment]
We have a lot of format issues in our js files that are not up to the 'standard'. That's what the linter is complaining about.

**Comment by mariotorres1** [comment]
https://standardjs.com/. This is what the error messages send as a potential fix to install and use.

**Comment by mariotorres1** [comment]
Fixed linter issues

**Review by mitchcrocker — APPROVED** [review]

**Review by katerosenthal — APPROVED** [review]

**Pull request merged**
