### PR TITLE
112 store a file temporarily

### PR DESCRIPTION
**Pull request by shuai-yang**
Currently, it works for .inp file but doesn't work for .csv.

### CODE REVIEW

**Comment by shuai-yang** [comment]
**There's the test results of parsed nodes and elements** 
image
image

**There's the link to the TIB_CART_MED_G.csv file**
https://drive.google.com/file/d/1o7W2qFZxCsylAj2sAYi13u6fLhpBXBfG/view?usp=sharing

**Review by katerosenthal — CHANGES_REQUESTED** [review]
Hey Sharon. This code still looks and works almost exactly like the parser I already made for the .inp files. It's still reading the file as a text file no matter what the original file type is (like I made it to), so I do think it may be a possible solution for our .csv files as well, but those will be the 'results' files and will need to be handled a bit differently. The input/geometry (.inp) files will never be formatted as .csv, so this was not really the issue here, and the results files should not be stored as nodes and elements, so this parser will not work for them as is. Mitch has also been working on parsing the .csv files on another branch/story.

I thought maybe you could just use/reference the section of my original code that reads the files in line by line to temporarily store the 'results'/.csv files as session data too, or test it out on the .csv files since I hadn't. That part is lines 25-39 in this version or lines 20-29 in the original parse-geometry.js I submitted.

I do like that you tidied up some unnecessary variables, though! Sorry for the confusion.

Edit- I took a minute to download the .csv file you linked and run it against my original parser and it does work fine and gets the same results, which is also good to know.

**Comment by shuai-yang** [comment]
> Hey Sharon. This code still looks and works almost exactly like the parser I already made for the .inp files. It's still reading the file as a text file no matter what the original file type is (like I made it to), so I do think it may be a possible solution for our .csv files as well, but those will be the 'results' files and will need to be handled a bit differently. The input/geometry (.inp) files will never be formatted as .csv, so this was not really the issue here, and the results files should not be stored as nodes and elements, so this parser will not work for them as is. Mitch has also been working on parsing the .csv files on another branch/story.
> 
> I thought maybe you could just use/reference the section of my original code that reads the files in line by line to temporarily store the 'results'/.csv files as session data too, or test it out on the .csv files since I hadn't. That part is lines 25-39 in this version or lines 20-29 in the original parse-geometry.js I submitted.
> 
> I do like that you tidied up some unnecessary comments and variables, though! Sorry for the confusion.
> 
> Edit- I took a minute to download the .csv file you linked and run it against my original parser and it does work fine and gets the same results, which is also good to know.

Could you send me the sample .csv file that you expect from the user? Otherwise, we have to close this story and make a new one which explicitly explains how .csv parser will be different from your .inp parser?

**Comment by katerosenthal** [comment]
Sorry. I tried to explain some in the comment before- the .csv files all contain different information than the .inp files, so they will either need an updated version of this/my parser, which I am totally willing to work on if we want. I only designed this parser to look through and separate geometry data. Not results data. The results data is what is in .csv format, but, like I think we found out, that might still work with this. It just wasn't tested or designed to. You shouldn't need to worry about any detailed parsing though. Mitch and I had the parsing tasks. While creating the parsing code, I accidentally came up with a decent solution for temporary file storage (reading it in as text line by line and storing those lines). I was just trying to share that solution with you to see if it helped your work with session storage for storing any/all files temporarily.

Also, our sponsors sent us a bunch of .csv files a month or so ago. I think we were all cc'd on it, but I can add them to the team docs folder after class today.

**Comment by katerosenthal** [comment]
PR closed without merging because the code submitted was a nearly exact duplicate of existing code and added no new functionality. Because the expected functionality for this branch/story was already partially implemented while creating a parser (https://github.com/cs481-ekh/f22-kneed-for-speed/pull/144), the rest of it will be addressed within a similar parsing story and different branch/future PR.

**Pull request closed without merging**
